### ISSUE TITLE
Link to 'Working with Overrides' topic is broken

### ISSUE THREAD

**Issue by tfelger** [Esri/dictionary-renderer-toolkit#1]
I am interested in the 'Working with Overrides' topic, but when I click on the link, I get the following message: 404-This is not the web page you are looking for.

Is the information for this topic available somewhere else? I have just started working with Symbol Dictionaries, and have gotten a lot of very helpful information from this site, and am hoping that the 'Overrides' topic is still available.

Thanks!

**Comment by fangli88** [comment]
@tfelger Try this link: https://github.com/Esri/dictionary-renderer-toolkit/blob/master/docs/working-with-overrides.md.

**Comment by williamscraigm** [comment]
Link should be fixed now.
