### ISSUE TITLE
Can I use Symbol Level Drawing with Symbol Dictionaries?

### ISSUE THREAD

**Issue by taetscher** [Esri/dictionary-renderer-toolkit#2]
Hello

I was wondering if it is possible to control Symbol Level Drawing with Symbol Dictionaries?
I couldn't find anything regarding this topic either in this repository or on the ESRI documentation pages for ArcGIS Pro.

Thank you
Ben

**Comment by williamscraigm** [comment]
This is not currently possible since symbol levels can vary greatly per drawn symbol. We will discuss if an approach could be possible.
